apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
  # superman@gmail.com
  PG_USER_EMAIL: c3VwZXJtYW5AZ21haWwuY29t
  # StrongPasswordHere
  PG_USER_PASSWORD: U3Ryb25nUGFzc3dvcmRIZXJl
