version: '3'

services:
  app:
    build:
      context: . # Especificar en donde buscar el Dockerfile
      target: ${STAGE}
      dockerfile: Dockerfile # Especificar el nombre del archivo (Por default es Dockerfile)
    volumes:
      - .:/app/ # Bind volume del proyecto

      # Crea un volumen anonimo que mapea el contenido del host con el directorio.
      # Modulos de node de manera anonima
      - /app/node_modules # En caso de que no exista la carpeta de node_modules
    container_name: nest-app
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
      HOST_API: ${HOST_API}
      JWT_SECRET: ${JWT_SECRET}

  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    external: false
